// FIXME: Update this file to be type safe and remove this and next line
// @ts-strict-ignore
import * as fs from "fs";
import * as path from "path";

import { app, ipcMain } from "electron";
import { firstValueFrom } from "rxjs";

import { autostart } from "@bitwarden/desktop-napi";

import { Main } from "../main";
import { DesktopSettingsService } from "../platform/services/desktop-settings.service";
import { isFlatpak, isSnapStore } from "../utils";

import { MenuUpdateRequest } from "./menu/menu.updater";

const SyncInterval = 5 * 60 * 1000; // 5 minutes
export const AUTOSTART_FLAG = "--autostart";

export class MessagingMain {
  private syncTimeout: NodeJS.Timeout;

  constructor(
    private main: Main,
    private desktopSettingsService: DesktopSettingsService,
  ) {}

  async init() {
    this.scheduleNextSync();

    // On app start, regenerate the configurations needed to autostart or not auto-start
    // depending on the setting provided in the settings file.
    const openAtLogin = await firstValueFrom(this.desktopSettingsService.openAtLogin$);
    if (openAtLogin) {
      this.addOpenAtLogin();
    } else {
      this.removeOpenAtLogin();
    }

    ipcMain.on(
      "messagingService",
      async (event: any, message: any) => await this.onMessage(message),
    );
  }

  async onMessage(message: any) {
    switch (message.command) {
      case "loadurl":
        // TODO: Remove this once fakepopup is removed from tray (just used for dev)
        await this.main.windowMain.loadUrl(message.url, message.modal);
        break;
      case "scheduleNextSync":
        this.scheduleNextSync();
        break;
      case "updateAppMenu":
        // FIXME: Verify that this floating promise is intentional. If it is, add an explanatory comment and ensure there is proper error handling.
        // eslint-disable-next-line @typescript-eslint/no-floating-promises
        this.main.menuMain.updateApplicationMenuState(message.updateRequest);
        this.updateTrayMenu(message.updateRequest);
        break;
      case "minimizeOnCopy":
        {
          const shouldMinimizeOnCopy = await firstValueFrom(
            this.desktopSettingsService.minimizeOnCopy$,
          );
          if (shouldMinimizeOnCopy && this.main.windowMain.win !== null) {
            this.main.windowMain.win.minimize();
          }
        }
        break;
      case "hideToTray":
        this.main.trayMain.hideToTray();
        break;
      case "addOpenAtLogin":
        this.addOpenAtLogin();
        break;
      case "removeOpenAtLogin":
        this.removeOpenAtLogin();
        break;
      case "setFocus":
        await this.setFocus();
        break;
      case "getWindowIsFocused":
        this.windowIsFocused();
        break;
      default:
        break;
    }
  }

  private scheduleNextSync() {
    if (this.syncTimeout) {
      global.clearTimeout(this.syncTimeout);
    }

    this.syncTimeout = global.setTimeout(() => {
      if (this.main.windowMain.win == null) {
        return;
      }

      this.main.windowMain.win.webContents.send("messagingService", {
        command: "checkSyncVault",
      });
    }, SyncInterval);
  }

  private updateTrayMenu(updateRequest: MenuUpdateRequest) {
    if (
      this.main.trayMain == null ||
      this.main.trayMain.contextMenu == null ||
      updateRequest?.activeUserId == null
    ) {
      return;
    }
    const lockVaultTrayMenuItem = this.main.trayMain.contextMenu.getMenuItemById("lockVault");
    const activeAccount = updateRequest.accounts[updateRequest.activeUserId];
    if (lockVaultTrayMenuItem != null && activeAccount != null) {
      lockVaultTrayMenuItem.enabled = activeAccount.isAuthenticated && !activeAccount.isLocked;
    }
    this.main.trayMain.updateContextMenu();
  }

  private addOpenAtLogin() {
    if (process.platform === "linux") {
      if (isFlatpak()) {
        autostart.setAutostart(true, ["bitwarden.sh", AUTOSTART_FLAG, "%U"]).catch((e) => {});
      } else if (isSnapStore()) {
        this.updateSnapAutostartExec();
      } else {
        const data = `[Desktop Entry]
  Type=Application
  Version=${app.getVersion()}
  Name=Bitwarden
  Comment=Bitwarden startup script
  Exec=${app.getPath("exe")} ${AUTOSTART_FLAG}
  StartupNotify=false
  Terminal=false`;

        const dir = path.dirname(this.linuxStartupFile());
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir);
        }
        fs.writeFileSync(this.linuxStartupFile(), data);
      }
    } else {
      app.setLoginItemSettings({ openAtLogin: true, args: [AUTOSTART_FLAG] });
    }
  }

  private updateSnapAutostartExec() {
    // Electron builder has the auto-start enabled flag set. This makes elecron builder tell snap that the .desktop file
    // placed in $SNAP_USER_DATA/.config/autostart should be auto-started. This file is auto-generated by electron-builder,
    // and must be edited, in order to set the autostart flag.
    const snapUserData = process.env.SNAP_USER_DATA;
    if (!snapUserData) {
      return;
    }

    const autostartDir = path.join(snapUserData, ".config", "autostart");
    if (!fs.existsSync(autostartDir)) {
      return;
    }

    const desktopFiles = fs
      .readdirSync(autostartDir)
      .filter((fileName) => fileName.endsWith(".desktop"));

    for (const desktopFileName of desktopFiles) {
      const desktopFilePath = path.join(autostartDir, desktopFileName);
      const existingData = fs.readFileSync(desktopFilePath, "utf8");
      const updatedData = this.setAutostartFlagOnDesktopFile(existingData);

      if (existingData !== updatedData) {
        fs.writeFileSync(desktopFilePath, updatedData);
      }
    }
  }

  /**
   * Sets the autostart flag on a linux .desktop file's Exec line.
   */
  private setAutostartFlagOnDesktopFile(desktopFileData: string): string {
    return desktopFileData
      .split("\n")
      .map((line) => line.trim())
      .map((line) => {
        if (line.startsWith("Exec=") && !line.includes(AUTOSTART_FLAG)) {
          return `${line} ${AUTOSTART_FLAG}`;
        }
        return line;
      })
      .join("\n");
  }

  private removeOpenAtLogin() {
    if (process.platform === "linux") {
      if (isFlatpak()) {
        autostart.setAutostart(false, []).catch((e) => {});
      } else {
        if (fs.existsSync(this.linuxStartupFile())) {
          fs.unlinkSync(this.linuxStartupFile());
        }
      }
    } else {
      app.setLoginItemSettings({ openAtLogin: false });
    }
  }

  private linuxStartupFile(): string {
    return path.join(app.getPath("home"), ".config", "autostart", "bitwarden.desktop");
  }

  private async setFocus() {
    await this.main.trayMain.restoreFromTray();
    this.main.windowMain.win.focusOnWebView();
  }

  private windowIsFocused() {
    const windowIsFocused = this.main.windowMain.win.isFocused();
    this.main.windowMain.win.webContents.send("messagingService", {
      command: "windowIsFocused",
      windowIsFocused: windowIsFocused,
    });
  }
}
